Dev/nytt endepunkt i smtp transport for henting av payload fra databasen
navikt/send-in-send-out pull request #21
Opened 2024-12-18 14:28 UTC by terjenilssen

Ønsker merge av nytt endpoint inn til main, selv om integrasjonstester ikke er laget ennå. Databaseoppsett må kanskje også endres (ikke verifisert).

2025-01-13 09:49 UTC, ivanskodje commented on ebms-send-in/build.gradle.kts
> +    }
Nice catch

2025-01-13 11:27 UTC, ivanskodje commented on felles/build.gradle.kts
>  }
Forstår ikke helt sammenhengen mellom din kommentar på punkt 2 og spørsmålet mitt  :thinking:  

Jeg lurte bare på om GitHub Action bygging blir å trigge ktlinting flere ganger (en gang ekstra unødvendig) som følge av dette

2025-01-20 08:08 UTC, kfh commented
> Kjempeflott opprydding og refaktorering! 🧹
> 
> For fremtidige endringer kan det være en god idé å lage egne pull requests kun for refaktorering før du gjør nye kodeendringer. Da blir det enklere (og raskere) å se alt i sammenheng og vurdere koden med klare forventninger.
> 
> Jeg har lagt inn et par kommentarer du kan se over, men alt i alt ser dette veldig bra ut! 👍

Jeg tror du blir forvirret av at @terjenilssen mest sannsynlig har gjort merge commit med veldig mange av mine endringer, @ivanskodje. Det er litt uheldig fordi gamle commits fra meg fremstår som en del av PR'en. @terjenilssen Når du merger bør du ALLTID rebase. Da legger du din egen kode på toppen av det som allerede finnes på _main_.

2025-01-20 08:27 UTC, kfh commented on felles/build.gradle.kts
>  }
Dette er jo produksjonskode. Vi trenger ikke ta høyde for lokale utviklingsmiljø. Dette kan du fint override lokalt selv.

2025-01-20 08:33 UTC, kfh commented on smtp-transport/src/main/kotlin/no/nav/emottak/AuthConfig.kt
> +            "api://${getEnvVar("NAIS_CLUSTER_NAME", "dev-fss")}.team-emottak.$appName/.default"
Alle `getEnvVar()` kall kan med fordel byttes ut med Hoplite. Det er allerede en integrert det av smtp-modulen.

2025-01-20 08:39 UTC, kfh commented on smtp-transport/src/main/kotlin/no/nav/emottak/plugin/Routes.kt
> +            throw BadRequestException(msg)
Hvorfor kaster du her ? Dette er jo en logisk feil(sett fra vårt domene) som vi har full kontroll på. Vi håndterer dette fint med Raise og evt sideeffekter som logging.

2025-01-20 08:43 UTC, kfh commented on smtp-transport/src/test/kotlin/no/nav/emottak/Database.kt
> +// Inspirert av: ebms-provider/src/test/kotlin/no/nav/emottak/ebms/DBTest.kt
Dette er jo basicly duplikat av hva som allerede finnes her. Skal ikke trenge og sette opp 2 forskjellige postgres-containere

2025-01-20 08:44 UTC, kfh commented on smtp-transport/src/test/kotlin/no/nav/emottak/Database.kt
> +fun PostgreSQLContainer<Nothing>.testConfiguration(): HikariConfig {
Det er sannsynligvis overflødig med connections pooling i tester. Tenker vi bare kan sløyfe denne.

2025-01-20 08:48 UTC, kfh commented on smtp-transport/src/test/kotlin/no/nav/emottak/SmtpTransportIntegrationTest.kt
> +class SmtpTransportIntegrationTest {
Jeg er lit usikker på om du trenger en full blown integrasjonstest her. Jeg har allerede testet persistens-laget relativt grundig gjennom PayloadRepositorySpec.

Hadde også gjerne sett at vi beholder samme type teststruktur. Fint om du mapper om denne til Kotest-standarden og bruker StringSpec. Det blir litt rotete med to forskjellige test-rammeverk i samme prosjekt. 

Jeg antar du har tatt litt inspirasjon av hva som allerede finnes i send-in-send-out, men smtp-modulen er strengt tatt en helt selvstendig, avgrenset modul med dedikert funksjonalitet. Planen er å flytte denne ut av send-in-send-out.

2025-01-20 08:51 UTC, kfh requested changes
Syntes du har løftet koden en god del siden vi snakket sammen sist uke og er på god vei til å fullføre denne. Bra jobba 👍 

Har lagt til noen kommentarer du kan titte over. Spesielt viktig å rydde opp i Git-historikken. Nå er det veldig mye kode som ikke tilhører din PR som dukker opp i Files Changed og det er litt vanskelig å skille på hva som tilhører dine eller andre sine commits.

2025-01-20 15:25 UTC, closed without merging